name: 'Continuous Integration'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Create virtualenv
        run: |
          make venv
      - name: Activate virtualenv
        run: |
          source venv/bin/activate
      - name: Install dependencies
        run: |
          make install
      - name: Run model-tests
        run: |
          make model-test
      - name: Run API tests
        run: |
          make api-test
      